#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
set -e
EXIT_CODE=0
echo Checking if everything is ok... 👀👀

if npm run build
then
  echo Maybe it is. Good Job! 🤠
  echo
  exit 0
else
  echo Something strange happened here!
  echo 🐞🐞🐞🐞🐞🐞
  echo
  exit 1
fi

